# Generated by Django 6.0.5 on 2026-05-11 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Imagen')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Descripcion')),
                ('add_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrada')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock/Cantidad')),
                ('cart', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL, verbose_name='Cesta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_supplied', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
