# Generated by Django 6.0.5 on 2026-05-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, verbose_name='Proveedor'),
        ),
    ]
