# Generated by Django 6.0.5 on 2026-05-12 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_description_products_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='exit_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de salida'),
            preserve_default=False,
        ),
    ]
