# Generated by Django 6.0.5 on 2026-05-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_cart_remove_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exit_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de salida'),
        ),
    ]
