# Generated by Django 6.0.5 on 2026-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_stock_stockmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='add_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='exit_at',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.AddField(
            model_name='products',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3),
        ),
    ]
