# Generated by Django 6.0.5 on 2026-05-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_add_at_remove_products_exit_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.CharField(blank=True, help_text='Razón del movimiento (ej. Factura #123, Inventario físico)', max_length=100),
        ),
    ]
